x#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           RightgoalMtr,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ArmMtrLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ClawMtr,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ArmMtrRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightbackMtr,  tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port7,           LeftfrontMtr,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightfrontMtr, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port9,           LeftgoalMtr,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.

	int prog;
	prog = 127;

 if (prog == 127)
 {
  motor(LeftfrontMtr) = 63;
  motor(RightbackMtr) = 63;
  motor(RightfrontMtr) = 63;
  wait1Msec(700);
  motor(LeftfrontMtr) = 0;
  motor(RightbackMtr) = 0;
  motor(RightfrontMtr) = 0;


  motor(ArmMtrLeft) = 63;
  motor(ArmMtrRight) = 63;
  wait1Msec(3000);
  motor(ArmMtrLeft) = 0;
  motor(ArmMtrRight) = 0;

  motor(LeftfrontMtr) = 63;
  motor(RightbackMtr) = 63;
  motor(RightfrontMtr) = 63;
  wait1Msec(2300);
  motor(LeftfrontMtr) = 0;
  motor(RightbackMtr) = 0;
  motor(RightfrontMtr) = 0;

  motor(RightgoalMtr) = 63;
  motor(LeftgoalMtr) = 63;
  wait1Msec(500);
  motor(RightgoalMtr) = -63;
  motor(LeftgoalMtr) = -63;
  wait1Msec(15000);

  motor(RightbackMtr) = -63;
  motor(LeftfrontMtr) = -61;
  motor(RightfrontMtr) = -63;
  wait1Msec(12000);
  motor(RightbackMtr) = 0;
  motor(LeftfrontMtr) = 0;
  motor(RightfrontMtr) = 0;

	}

}



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void everything()
{
	while(true)
	{
		{
			if (vexRT[Btn7R] == 1)
			{
				motor(ClawMtr) = 25;
				wait1Msec(600);
				motor(ClawMtr) = 0;
			}
			else if(vexRT[Btn7L] == 1)
			{
				motor(ClawMtr) = -25;
				wait1Msec(600);
				motor(ClawMtr) = 0;
			}
			else
			{
				motor(ClawMtr) = 0;
			}
			if (abs(vexRT[Ch2]) > 20)
			{
				motor[RightbackMtr] = vexRT[Ch2]/1.3;
				motor[RightfrontMtr] = vexRT[Ch2]/1.3;
			}

			else if (abs(vexRT[Ch2]) <= 20)
			{
				motor[RightbackMtr] = 0;
				motor[RightfrontMtr] = 0;
			}


			if (abs(vexRT[Ch3]) > 20)
			{
				motor[LeftfrontMtr] = vexRT[Ch3]/1.3;
			}

			else if (abs(vexRT[Ch3]) <= 20)
			{
				motor[LeftfrontMtr] = 0;
			}

			if (vexRT[Btn6D] == 1)
			{
				motor(ArmMtrLeft) = 80;
				motor(ArmMtrRight) = 80;
			}
			else if (vexRT[Btn6U] == 1)
			{
				motor(ArmMtrLeft) = -80;
				motor(ArmMtrRight) = -80;
			}
			else
			{
				motor(ArmMtrLeft) = 0;
				motor(ArmMtrRight) = 0;
			}


			if (vexRT[Btn5U] == 1)
			{
				motor(LeftgoalMtr) = 127; //This speed will change as it is the speed of the mobile goal holder move.
				motor(RightgoalMtr) = 127; //Same here.
			}
			else if (vexRT[Btn5D] == 1)
			{
				motor(LeftgoalMtr) = -127;
				motor(RightgoalMtr) = -127;
			}
			else
			{
				motor(LeftgoalMtr) = 0;
				motor(RightgoalMtr) = 0;
			}

		}
	}
}

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	everything();
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.

  }
}
